# config
logo: /images/logo.png
menu:
  首页: ' '
  文章: articles
  记录: notes
  阅读: readings
  标签: tags
  关于: author

# Content
excerpt_link: Read More

# Miscellaneous
rss: /atom.xml
google_analytics: false
